.\" Manpage for maclookup.
.\" Contact shulepov@gmail.com to correct errors.
.TH man 8 "20 October  2020" "1.0" "maclookup man page"
.SH NAME
maclookup \- lookup vendor by MAC address 
.SH SYNOPSIS
maclookup [-chiu] XX:XX:XX[XX:XX:XX]
.SH DESCRIPTION
maclookup shell program for lookup vendor by MAC address. Search first 3 byte of hardware address in oui.txt
.SH OPTIONS
.PP
.TP
\fB\-c\fR\ create config file
.TP
\fB\-h\fR\ display help
.TP
\fB\-i\fR\ display configuration info from config file
.TP
\fB\-u\fR\ update oui.txt from web
.SH SEE ALSO
nmap(8), ieee-data(8)
.SH BUGS
No known bugs
.SH AUTHOR
Shulepov Oleg (shulepov@gmail.com)
